export const CONTINENETS_FETCH_REQUEST = "CONTINENETS_FETCH_REQUEST";
export const CONTINENETS_FETCH_SUCCESS = "CONTINENETS_FETCH_SUCCESS";
export const CONTINENETS_FETCH_FAILURE = "CONTINENETS_FETCH_FAILURE";
export const CONTINENET_FETCH_REQUEST = "CONTINENET_FETCH_REQUEST";
export const CONTINENET_FETCH_SUCCESS = "CONTINENET_FETCH_SUCCESS";
export const CONTINENET_FETCH_FAILURE = "CONTINENET_FETCH_FAILURE";